services:
    db:
        image: postgres:latest
        ports:
        - '5432:5432'
        environment:
          POSTGRES_USER: ben
          POSTGRES_PASSWORD: asdfasdfasdf
          POSTGRES_DB: postgres
        volumes:
        - db:/var/lib/postgresql/data

volumes:
  db: